import fs from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import type { Habit } from "../lib/focus-flow/types";
import { getHabitTimerProgress, isHabitCompleteOn, isHabitTimeReady } from "../lib/focus-flow/utils";
const source = (...segments: string[]) => fs.readFileSync(resolve(__dirname, "..", ...segments), "utf8");
const date = "2026-08-27"; const startedAt = "2026-08-27T10:00:00.000Z"; const runningHabit: Habit = { id: "run", title: "ランニング", color: "#16725C", goalPerWeek: 5, isRequired: true, completedDates: [], progressUnit: "minutes", targetValue: 30, timerStartedAtByDate: { [date]: startedAt }, timerElapsedSecondsByDate: {}, createdAt: startedAt }; const pausedHabit: Habit = { ...runningHabit, timerStartedAtByDate: {}, timerElapsedSecondsByDate: { [date]: 307 } };
describe("時間型Habitの計測・手動完了・Widget契約", () => {
  it("実時間と停止済み時間を合算し、停止中は経過せず再開可能な状態を導出する", () => { expect(getHabitTimerProgress(runningHabit, date, new Date("2026-08-27T10:05:07.000Z"))).toMatchObject({ started: true, running: true, paused: false, ready: false, elapsedSeconds: 307, remainingSeconds: 1493, label: "05:07 / 30:00" }); expect(getHabitTimerProgress(pausedHabit, date, new Date("2026-08-27T11:10:00.000Z"))).toMatchObject({ started: true, running: false, paused: true, elapsedSeconds: 307 }); expect(isHabitTimeReady(runningHabit, date, new Date("2026-08-27T10:30:00.000Z"))).toBe(true); expect(isHabitCompleteOn(runningHabit, date, new Date("2026-08-27T10:30:00.000Z"))).toBe(false); });
  it("TodayとHabitは共有HabitItemCardを通じて共通の開始・停止・再開コントロールを利用する", () => { const today = source("app", "(tabs)", "index.tsx"); const habits = source("app", "(tabs)", "habits.tsx"); const card = source("components", "focus-flow", "item-cards.tsx"); const control = source("components", "focus-flow", "habit-progress-control.tsx"); [today, habits].forEach((screen) => { expect(screen).toContain("<HabitItemCard"); expect(screen).toContain("startHabitTimer"); expect(screen).toContain("pauseHabitTimer"); }); ["HabitProgressControl", "onPauseTimer"].forEach((text) => expect(card).toContain(text)); ['unit === "minutes"', "timer.paused", 'name={timer.running ? "pause" : "play-arrow"}', "onPauseTimer"].forEach((text) => expect(control).toContain(text)); });
  it("Widgetの時間型Habitは開始・停止・再開と保存済み経過を扱う", () => { const provider = source("plugins", "native", "android", "kotlin", "FocusFlowWidgetProvider.kt"); const gate = source("plugins", "native", "android", "kotlin", "FocusGateModule.kt"); const bridge = source("lib", "focus-flow", "android-gate.ts"); ["ACTION_TIMER_PAUSE", '"timer_pause"', "timerPaused", "timerElapsedSeconds", "timerStartedAtMillis", "setChronometer(ids.chronometer"].forEach((text) => expect(provider).toContain(text)); expect(gate).toContain('action.takeIf { it.has("elapsedSeconds") }'); expect(bridge).toContain('"timer_pause"'); });
});
