import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
const read = (...parts: string[]) => fs.readFileSync(path.join(process.cwd(), ...parts), "utf8");
describe("Focus Flowカード密度", () => {
  it("Todo・習慣・Todayは「必須」をフル表示する共有ピルと44dpチェック領域を使う", () => { const cards = read("components", "focus-flow", "item-cards.tsx"); const today = read("app", "(tabs)", "index.tsx"); expect(cards).toContain('checkTouchTarget: { width: 44, height: 44'); expect(cards).toContain('const displayLabel = label === "Must-do" ? label : "必須"'); expect(cards).toContain('allowFontScaling={false}'); expect(cards).toContain('requiredLabelJapanese: { width: 44 }'); expect(cards).toContain('todoDue: { minWidth: 44'); expect(cards).toContain('todoRow: { position: "relative", minHeight: 66'); expect(cards).toContain('habitRow: { position: "relative", minHeight: 66'); expect(today).toContain("<TodoItemCard"); expect(today).toContain("<HabitItemCard"); });
  it("静的Widgetは52dp見出しと48dpの連続行を最大3行表示し、Collectionを使わない", () => { const layout = read("plugins", "native", "android", "res", "layout", "focus_flow_widget_initial.xml"); expect(layout).toContain('android:layout_height="52dp"'); expect((layout.match(/android:layout_height="48dp"/g) ?? []).length).toBeGreaterThanOrEqual(4); expect(layout).toContain('android:layout_height="1dp"'); expect(layout).not.toContain('android:layout_marginStart="7dp"'); expect(layout).not.toContain("ListView"); });
  it("時間型HabitはRemoteViews Chronometerでライブ計測を維持する", () => { const provider = read("plugins", "native", "android", "kotlin", "FocusFlowWidgetProvider.kt"); ["setChronometer(ids.chronometer", "SystemClock.elapsedRealtime()", "timerStartedAtMillis"].forEach((text) => expect(provider).toContain(text)); });
  it("完了済み項目は取り消し線・淡い面・可読文字で区別する", () => { const cards = read("components", "focus-flow", "item-cards.tsx"); expect(cards).toContain('backgroundColor: achieved ? palette.elevated : palette.surface'); expect(cards).toContain('textDecorationColor: palette.muted'); expect(cards).not.toMatch(/taskRowDone: \{ opacity|habitRowDone: \{ opacity/); });
});
