import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
const read = (...parts: string[]) => fs.readFileSync(path.join(process.cwd(), ...parts), "utf8");
describe("Focus Flow Androidネイティブプラグイン", () => {
  it("Widgetは静的RemoteViews・直接操作・リサイズを維持する", () => { const provider = read("plugins", "native", "android", "kotlin", "FocusFlowWidgetProvider.kt"); const module = read("plugins", "native", "android", "kotlin", "FocusGateModule.kt"); ["class FocusFlowWidgetProvider : AppWidgetProvider()", "bindStaticRows", "StaticRowIds", "onAppWidgetOptionsChanged", "ACTION_COMPLETE", "ACTION_RESTORE", "ACTION_TIMER_START", "ACTION_TIMER_PAUSE", "WIDGET_ACTIONS", "WidgetBucket(5"].forEach((text) => expect(provider).toContain(text)); expect(provider).not.toContain("setRemoteAdapter"); expect(provider).not.toContain("class FocusFlowWidgetItemsService"); expect(module).toContain("consumeWidgetActions"); });
  it("クリーン生成はProviderを登録し、旧Collection ServiceをManifestへ戻さない", () => { const plugin = read("plugins", "with-focus-flow-android.js"); expect(plugin).toContain("focus_flow_widget_initial.xml"); expect(plugin).toContain("FocusFlowWidgetProvider"); expect(plugin).not.toContain('"FocusFlowWidgetItemsService.kt"'); expect(plugin).not.toContain('"android.permission.BIND_REMOTEVIEWS"'); });
  it("初期layoutは許容Viewだけで、52dp見出しと48dp連続行を持つ", () => { const layout = read("plugins", "native", "android", "res", "layout", "focus_flow_widget_initial.xml"); const info = read("plugins", "native", "android", "res", "xml", "focus_flow_widget_initial_info.xml"); expect(info).toContain('@layout/focus_flow_widget_initial'); ["<FrameLayout", "<LinearLayout", "<TextView", "<ImageView", "<Chronometer", 'android:layout_height="52dp"', 'android:layout_height="48dp"'].forEach((text) => expect(layout).toContain(text)); expect(layout).not.toContain("<View"); expect(layout).not.toContain("ListView"); expect(layout).not.toContain("android:layout_weight"); expect(layout).not.toContain('="0dp"'); });
});
