import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
const read = (...segments: string[]) => fs.readFileSync(path.join(process.cwd(), ...segments), "utf8");
describe("Focus Flow Widgetとテーマ可読性", () => {
  it("静的Widgetは文字サイズ、必須タグ、時間型Habit操作を維持する", () => { const provider = read("plugins", "native", "android", "kotlin", "FocusFlowWidgetProvider.kt"); const layout = read("plugins", "native", "android", "res", "layout", "focus_flow_widget_initial.xml"); ["state.optString(\"widgetTextScale\", \"standard\")", "val timerRunning = item.optBoolean", "val timerPaused = item.optBoolean", "compactBadge", 'required -> if (english) "MUST" else "必須"'].forEach((text) => expect(provider).toContain(text)); ["android:layout_height=\"52dp\"", "android:layout_height=\"48dp\"", "android:gravity=\"center_vertical\"", "android:maxLines=\"1\""].forEach((text) => expect(layout).toContain(text)); });
  it("Widgetはlight・darkのパレット色を背景・見出し・行へ適用し、二層透過でも文字を退色させない", () => { const provider = read("plugins", "native", "android", "kotlin", "FocusFlowWidgetProvider.kt"); const bridge = read("lib", "focus-flow", "android-gate.ts"); ["paletteColor(palette, \"text\"", "paletteColor(palette, \"muted\"", "paletteColor(palette, \"primarySoft\"", "colorWithOpacity", "setBackgroundColor", "setChronometer(ids.chronometer"].forEach((text) => expect(provider).toContain(text)); ["widgetBackgroundOpacity", "widgetCardOpacity", "widgetPalette"].forEach((text) => expect(bridge).toContain(text)); expect(provider).not.toContain('setFloat('); });
  it("Widgetの今日の項目はprimaryを混ぜたテーマ別アクセント背景と見出し色を使う", () => { const provider = read("plugins", "native", "android", "kotlin", "FocusFlowWidgetProvider.kt"); expect(provider).toContain('val primary = paletteColor(palette, "primary"'); expect(provider).toContain("val headerSurface = blendColors(background, primary"); expect(provider).toContain("if (dark) 0.36f else 0.30f"); expect(provider).toContain("setBackgroundColor",); expect(provider).toContain("val title = primary"); expect(provider).toContain("setTextColor(R.id.focus_flow_widget_title, title)"); });
  it("長い日本語見出しは件数バッジや追加ボタンに隠れず省略表示できる", () => { const habits = read("app", "(tabs)", "habits.tsx"); const ui = read("components", "focus-flow", "ui.tsx"); expect(habits).toContain('numberOfLines={1} ellipsizeMode="tail"'); expect(habits).toContain("groupTitle: { flex: 1, minWidth: 0"); expect(ui).toContain("headingCopy: { flex: 1, minWidth: 0"); });
  it("外観設定は本体とWidgetのテーマを接続し、共通テキストを動的paletteへ解決する", () => { const root = read("app", "_layout.tsx"); const text = read("components", "focus-flow", "scaled-text.tsx"); ["FocusFlowThemeBridge", "resolveAppearance(displaySettings, systemScheme)", "getAppPalette(displaySettings, systemScheme)"].forEach((value) => expect(root).toContain(value)); ["semanticTextColor", "palette.primary", "palette.text", "palette.muted"].forEach((value) => expect(text).toContain(value)); });
  it("主要画面と編集シートは固定白面ではなく動的paletteを利用する", () => { [read("app", "(tabs)", "index.tsx"), read("app", "(tabs)", "todos.tsx"), read("app", "(tabs)", "habits.tsx"), read("components", "focus-flow", "task-form.tsx")].forEach((source) => { expect(source).toContain("useFocusPalette"); expect(source.includes("palette.surface") || source.includes("palette.primarySoft")).toBe(true); expect(source).toContain("palette.border"); }); });
});
