import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
const source = (...segments: string[]) => readFileSync(resolve(__dirname, "..", ...segments), "utf8");
describe("実機視覚品質の静的契約", () => {
  it("WidgetはRemoteViewsが許容するViewだけで構成し、色を背景と項目行へ直接適用する", () => { const layout = source("plugins", "native", "android", "res", "layout", "focus_flow_widget_initial.xml"); const provider = source("plugins", "native", "android", "kotlin", "FocusFlowWidgetProvider.kt"); expect(layout).not.toMatch(/<View[\s>]/); expect(layout).toContain("focus_flow_widget_static_divider_one"); expect(layout).toContain('android:id="@+id/focus_flow_widget_card"'); expect(provider).not.toContain('setFloat(R.id.focus_flow_widget_card_background, "setAlpha"'); expect(provider).not.toContain('setFloat(ids.check, "setAlpha"'); expect(provider).toContain("colorWithOpacity"); expect(provider).toContain("setBackgroundColor"); });
  it("必須Pillは日本語と英語で共有カードから表示し、チェック領域は固定44dpを保つ", () => { const ui = source("components", "focus-flow", "ui.tsx"); const cards = source("components", "focus-flow", "item-cards.tsx"); expect(ui).toContain("minWidth: 76"); expect(ui).toContain("allowFontScaling={false}"); expect(cards).toContain('Pill label={t("必須", "Must-do")}'); expect(cards).toContain('checkTouchTarget: { width: 44, height: 44'); });
  it("表示と言語はpaletteを入力・選択肢・カードへ渡し、Widget透過は二層スライダーで調整する", () => { const settings = source("app", "(tabs)", "settings.tsx"); expect(settings).toContain("const palette = useFocusPalette()"); expect(settings).toContain("backgroundColor: palette.surface"); expect(settings).toContain("borderColor: palette.border"); expect(settings).toContain("function OpacitySlider"); expect(settings).toContain("widgetBackgroundOpacity"); expect(settings).toContain("widgetCardOpacity"); });
});
