import type { AppThemeId, AppearancePreference, DisplaySettings } from "./types";

export type AppPalette = { background: string; surface: string; elevated: string; text: string; muted: string; border: string; primary: string; primarySoft: string; tab: string; isDark: boolean };

type ThemeDefinition = { premium: boolean; label: { ja: string; en: string }; light: AppPalette; dark: AppPalette };

export const APP_THEMES: Record<AppThemeId, ThemeDefinition> = {
  mist: { premium: false, label: { ja: "ミスト", en: "Mist" }, light: { background: "#F7F8F5", surface: "#FFFFFF", elevated: "#EDF4F0", text: "#1A2925", muted: "#64736D", border: "#D7E2DD", primary: "#1B6B62", primarySoft: "#E3F1EC", tab: "#F9FBFA", isDark: false }, dark: { background: "#14231F", surface: "#1C302A", elevated: "#263E36", text: "#F2FAF6", muted: "#B3C7BE", border: "#3B554B", primary: "#7FCBB0", primarySoft: "#23483C", tab: "#182A24", isDark: true } },
  slate: { premium: false, label: { ja: "スレート", en: "Slate" }, light: { background: "#F3F6FB", surface: "#FFFFFF", elevated: "#E9EFF7", text: "#15233B", muted: "#617089", border: "#D7E1F0", primary: "#3566B7", primarySoft: "#E7EFFD", tab: "#F7FAFF", isDark: false }, dark: { background: "#17212E", surface: "#202D3C", elevated: "#2A3B50", text: "#F0F5FC", muted: "#B6C4D6", border: "#40536B", primary: "#86B4FF", primarySoft: "#263F63", tab: "#1B2735", isDark: true } },
  evergreen: { premium: true, label: { ja: "エバーグリーン", en: "Evergreen" }, light: { background: "#F1F7F3", surface: "#FFFFFF", elevated: "#E0F0E6", text: "#153126", muted: "#587064", border: "#C9DED1", primary: "#23724D", primarySoft: "#DDF1E4", tab: "#F7FCF8", isDark: false }, dark: { background: "#102B20", surface: "#18392A", elevated: "#204A36", text: "#EDFAF1", muted: "#B0CCBD", border: "#3B604D", primary: "#83D5A7", primarySoft: "#1D5138", tab: "#153324", isDark: true } },
  ocean: { premium: true, label: { ja: "オーシャン", en: "Ocean" }, light: { background: "#F1F7FB", surface: "#FFFFFF", elevated: "#E2F0F8", text: "#153044", muted: "#597486", border: "#C9DDE9", primary: "#28769F", primarySoft: "#DDEFF8", tab: "#F7FCFF", isDark: false }, dark: { background: "#112D3C", surface: "#183B4D", elevated: "#214D63", text: "#EEF9FF", muted: "#B1D1DE", border: "#3C6476", primary: "#7FC8EA", primarySoft: "#1B5470", tab: "#163545", isDark: true } },
  orchid: { premium: true, label: { ja: "オーキッド", en: "Orchid" }, light: { background: "#F8F4FA", surface: "#FFFFFF", elevated: "#F0E7F4", text: "#32233D", muted: "#756783", border: "#E0D1E8", primary: "#7A5195", primarySoft: "#F0E2F6", tab: "#FCF8FD", isDark: false }, dark: { background: "#2B2033", surface: "#382845", elevated: "#4A3559", text: "#FBF1FF", muted: "#D3BEDF", border: "#644E73", primary: "#D4A8ED", primarySoft: "#553A67", tab: "#34253F", isDark: true } },
  sunrise: { premium: true, label: { ja: "サンライズ", en: "Sunrise" }, light: { background: "#FFF8F0", surface: "#FFFFFF", elevated: "#FDF0DE", text: "#412D1E", muted: "#7C6859", border: "#ECD9C5", primary: "#B35F35", primarySoft: "#FBE5D8", tab: "#FFFBF6", isDark: false }, dark: { background: "#36251D", surface: "#453128", elevated: "#593E31", text: "#FFF5EC", muted: "#E1C5B1", border: "#735746", primary: "#F1AD83", primarySoft: "#6B4532", tab: "#402C23", isDark: true } },
};

export function isPremiumAppTheme(theme: AppThemeId) { return APP_THEMES[theme].premium; }
export function resolvedAppTheme(settings: DisplaySettings): AppThemeId { return settings.appTheme ?? settings.theme ?? "mist"; }
export function resolveAppearance(settings: DisplaySettings, system: "light" | "dark"): "light" | "dark" { return settings.appearance === "light" || settings.appearance === "dark" ? settings.appearance : system; }
export function getAppPalette(settings: DisplaySettings, system: "light" | "dark"): AppPalette { const theme = resolvedAppTheme(settings); return APP_THEMES[theme][resolveAppearance(settings, system)]; }
export const APPEARANCE_OPTIONS: AppearancePreference[] = ["system", "light", "dark"];
