import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Platform, Share, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from "react-native";

import { ScaledText as Text } from "@/components/focus-flow/scaled-text";
import { COLORS } from "@/components/focus-flow/ui";
import { ScreenContainer } from "@/components/screen-container";
import { getGateDiagnostics, type GateDiagnostics } from "@/lib/focus-flow/android-gate";

const FAQS = [
  { question: "What do App limits do?", answer: "App limits keep the apps you choose locked until you complete your must-do tasks and habits. You decide when limits apply by setting schedules in Settings." },
  { question: "Why isn't an app being locked?", answer: "Check that App limits are on, the current time is inside an active schedule, the app is selected in that schedule, and Accessibility is enabled. Battery settings can also prevent Android from running limits reliably." },
  { question: "How do I turn off App limits?", answer: "Open Manage, then Settings. You can turn off App limits at any time. You can also disable Accessibility in Android settings." },
  { question: "Why does Focus Flow need Accessibility?", answer: "Accessibility lets Focus Flow detect when a selected app opens so it can apply your App limits. It does not read screen text, messages, typed content, or screenshots." },
  { question: "What data leaves my device?", answer: "In this beta, your tasks, notes, routines, and app activity stay on your device. Focus Flow does not use advertising or behavioral-tracking SDKs." },
  { question: "What if I am locked out by mistake?", answer: "On the limit screen, choose Pause limits for 10 minutes. Then open Settings to check your schedule, selected apps, and device diagnostics." },
  { question: "How can I report a problem?", answer: "Use the template below. It includes non-sensitive device and permission details to help reproduce the issue. Do not include task or note content." },
];

function status(value: boolean | null | undefined) { return value === null || value === undefined ? "Unknown" : value ? "Yes" : "No"; }

export default function SupportScreen() {
  const router = useRouter();
  const [openQuestion, setOpenQuestion] = useState<number | null>(0);
  const [diagnostics, setDiagnostics] = useState<GateDiagnostics | undefined>();
  const [loading, setLoading] = useState(true);
  const loadDiagnostics = async () => { setLoading(true); try { setDiagnostics(await getGateDiagnostics()); } finally { setLoading(false); } };
  useEffect(() => { void loadDiagnostics(); }, []);
  const report = useMemo(() => {
    const device = diagnostics ? `${diagnostics.manufacturer} ${diagnostics.model}` : "Not available";
    const android = diagnostics ? `Android API ${diagnostics.apiLevel}` : Platform.OS === "android" ? `Android ${String(Platform.Version)}` : Platform.OS;
    return ["Focus Flow beta bug report", "", "What happened?", "[Describe what you saw]", "", "What did you expect to happen?", "[Describe the expected result]", "", "Steps to reproduce", "1. [First step]", "2. [Next step]", "3. [What happened]", "", "Device details", `- Device: ${device}`, `- OS: ${android}`, `- Accessibility enabled: ${status(diagnostics?.accessibilityEnabled)}`, `- Battery optimization ignored: ${status(diagnostics?.batteryOptimizationIgnored)}`, `- Background restricted: ${status(diagnostics?.backgroundRestricted)}`, `- Temporary pause active: ${diagnostics?.safetyPauseUntil && diagnostics.safetyPauseUntil > Date.now() ? "Yes" : "No"}`, "", "Optional", "- Screenshot or screen recording: [Attach if it does not show private task or note content]", "- Anything else that may help us reproduce it:"].join("\n");
  }, [diagnostics]);
  const shareReport = async () => { await Share.share({ title: "Focus Flow beta bug report", message: report }); };

  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Back to Manage" onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color={COLORS.forest} /><Text style={styles.backText}>Back to Manage</Text></TouchableOpacity><Text style={styles.eyebrow}>SUPPORT</Text><Text style={styles.title}>FAQ & bug reports</Text><Text style={styles.intro}>Find quick answers, then send a clear report if something does not work as expected.</Text><Text style={styles.sectionTitle}>Frequently asked questions</Text><View style={styles.faqGroup}>{FAQS.map((faq, index) => { const open = openQuestion === index; return <View key={faq.question} style={[styles.faqItem, open && styles.faqOpen]}><TouchableOpacity accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={() => setOpenQuestion(open ? null : index)} style={styles.faqButton}><Text style={styles.faqQuestion}>{faq.question}</Text><MaterialIcons name={open ? "keyboard-arrow-up" : "keyboard-arrow-down"} size={22} color={COLORS.forest} /></TouchableOpacity>{open ? <Text style={styles.faqAnswer}>{faq.answer}</Text> : null}</View>; })}</View><View style={styles.reportHeader}><View style={styles.reportIcon}><MaterialIcons name="bug-report" size={21} color={COLORS.blue} /></View><View style={styles.reportCopy}><Text style={styles.sectionTitle}>Report a problem</Text><Text style={styles.reportIntro}>This template adds device and App limits details without including your tasks or notes.</Text></View></View><TouchableOpacity accessibilityRole="button" onPress={() => void loadDiagnostics()} style={styles.refreshButton}><MaterialIcons name="refresh" size={18} color={COLORS.forest} /><Text style={styles.refreshText}>{loading ? "Checking device info…" : "Refresh device info"}</Text>{loading ? <ActivityIndicator size="small" color={COLORS.forest} /> : null}</TouchableOpacity><Text style={styles.templateLabel}>Copy or share this template</Text><TextInput value={report} editable={false} selectTextOnFocus multiline style={styles.template} accessibilityLabel="Bug report template" /><TouchableOpacity accessibilityRole="button" onPress={() => void shareReport()} style={styles.shareButton}><MaterialIcons name="ios-share" size={19} color={COLORS.white} /><Text style={styles.shareText}>Share report</Text></TouchableOpacity><Text style={styles.privacyNote}>Before you share, remove anything private. Do not include task titles, note content, or screenshots containing sensitive information.</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 14, paddingBottom: 42 }, back: { minHeight: 40, alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 2 }, backText: { color: COLORS.forest, fontSize: 13, fontWeight: "800" }, eyebrow: { color: COLORS.forest, fontSize: 12, letterSpacing: 0.7, fontWeight: "900", marginTop: 9 }, title: { color: COLORS.text, fontSize: 28, lineHeight: 34, letterSpacing: -0.5, fontWeight: "900", marginTop: 2 }, intro: { color: COLORS.muted, fontSize: 14, lineHeight: 21, marginTop: 7, maxWidth: 540 }, sectionTitle: { color: COLORS.text, fontSize: 18, lineHeight: 24, fontWeight: "900", marginTop: 26 }, faqGroup: { borderWidth: 1, borderColor: COLORS.border, borderRadius: 18, overflow: "hidden", backgroundColor: COLORS.white, marginTop: 10 }, faqItem: { borderBottomWidth: 1, borderBottomColor: "#E5ECE8" }, faqOpen: { backgroundColor: "#F0F7F4" }, faqButton: { minHeight: 57, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 14, paddingVertical: 10 }, faqQuestion: { flex: 1, color: COLORS.text, fontSize: 14, lineHeight: 20, fontWeight: "800" }, faqAnswer: { color: "#46645B", fontSize: 13, lineHeight: 20, paddingHorizontal: 14, paddingBottom: 15 }, reportHeader: { flexDirection: "row", gap: 11, marginTop: 30 }, reportIcon: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#E8F0FB" }, reportCopy: { flex: 1 }, reportIntro: { color: COLORS.muted, fontSize: 13, lineHeight: 19, marginTop: 3 }, refreshButton: { minHeight: 45, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 13, backgroundColor: "#EAF5F1", marginTop: 14, paddingHorizontal: 12 }, refreshText: { color: COLORS.forest, fontSize: 13, fontWeight: "800" }, templateLabel: { color: COLORS.text, fontSize: 13, fontWeight: "800", marginTop: 17, marginBottom: 7 }, template: { minHeight: 278, borderRadius: 15, borderWidth: 1, borderColor: "#CADAD4", backgroundColor: COLORS.white, color: COLORS.text, fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 12, lineHeight: 18, padding: 13, textAlignVertical: "top" }, shareButton: { minHeight: 51, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 15, backgroundColor: COLORS.forest, marginTop: 12 }, shareText: { color: COLORS.white, fontSize: 15, fontWeight: "900" }, privacyNote: { color: COLORS.muted, fontSize: 11, lineHeight: 16, marginTop: 10, textAlign: "center" } });
