import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FlatList, StyleSheet, TouchableOpacity, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";

import { HabitForm } from "@/components/focus-flow/habit-form";
import { HabitItemCard, TodoItemCard } from "@/components/focus-flow/item-cards";
import { TaskForm } from "@/components/focus-flow/task-form";
import { ScaledText as Text } from "@/components/focus-flow/scaled-text";
import { COLORS, IconButton, LoadingScreen, safeHaptic, useFocusPalette } from "@/components/focus-flow/ui";
import { ScreenContainer } from "@/components/screen-container";
import { isEnglish } from "@/lib/focus-flow/i18n";
import { useFocusFlow } from "@/lib/focus-flow/provider";
import type { Habit, Todo } from "@/lib/focus-flow/types";
import { dayKey, getGateRuleSummaries, getGateSummary, isHabitCompleteOn, isTodoAchieved, isTodoEffectiveRequired } from "@/lib/focus-flow/utils";

type HomeListItem = { type: "heading"; id: string; title: string; detail: string } | { type: "todo"; id: string; todo: Todo } | { type: "habit"; id: string; habit: Habit };

export default function TodayScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ completed?: string | string[] }>();
  const { todos, habits, memos, focusSessions, gateConfig, displaySettings, isReady, toggleTodo, toggleSubtask, toggleHabit, startHabitTimer, pauseHabitTimer, adjustHabitProgress, addTodo, updateTodo, updateHabit } = useFocusFlow();
  const palette = useFocusPalette(); const [taskFormOpen, setTaskFormOpen] = useState(false); const [newTaskDefaultRequired, setNewTaskDefaultRequired] = useState(false); const [openedTodo, setOpenedTodo] = useState<Todo | undefined>(); const [openedHabit, setOpenedHabit] = useState<Habit | undefined>(); const [showCompleted, setShowCompleted] = useState(false); const english = isEnglish(displaySettings); const today = dayKey(); const t = useCallback((ja: string, en: string) => english ? en : ja, [english]);
  useEffect(() => { const reveal = Array.isArray(params.completed) ? params.completed[0] : params.completed; if (reveal === "1") setShowCompleted(true); }, [params.completed]);
  const gateSummary = useMemo(() => getGateSummary({ todos, habits, memos, focusSessions, gateConfig, displaySettings }, new Date(), english ? "en" : "ja"), [todos, habits, memos, focusSessions, gateConfig, displaySettings, english]); const activeRules = useMemo(() => getGateRuleSummaries({ todos, habits, memos, focusSessions, gateConfig, displaySettings }, new Date(), english ? "en" : "ja").filter((rule) => rule.isActive), [todos, habits, memos, focusSessions, gateConfig, displaySettings, english]);
  const effectiveTodos = useMemo(() => todos.filter((todo) => isTodoEffectiveRequired(todo)), [todos]); const effectiveHabits = useMemo(() => habits.filter((habit) => habit.isRequired), [habits]); const openTodos = effectiveTodos.filter((todo) => !isTodoAchieved(todo)); const openHabits = effectiveHabits.filter((habit) => !isHabitCompleteOn(habit, today)); const doneTodos = useMemo(() => effectiveTodos.filter((todo) => isTodoAchieved(todo)), [effectiveTodos]); const doneHabits = useMemo(() => effectiveHabits.filter((habit) => isHabitCompleteOn(habit, today)), [effectiveHabits, today]); const hiddenCompletedCount = doneTodos.length + doneHabits.length;
  const pendingRequired = openTodos.length + openHabits.length; const totalRequired = effectiveTodos.length + effectiveHabits.length; const doneRequired = Math.max(totalRequired - pendingRequired, 0); const timeActive = activeRules.some((rule) => rule.id === "always" || Boolean(rule.schedule)); const gateLocked = gateConfig.enabled && timeActive && gateSummary.pendingCount > 0; const progressForeground = palette.isDark ? palette.text : COLORS.white;
  const listItems = useMemo<HomeListItem[]>(() => { const result: HomeListItem[] = []; if (openTodos.length || openHabits.length) result.push({ type: "heading", id: "today-open", title: t("今日の対象", "Today’s focus"), detail: t("必須と今日までのTodoです", "Must-dos and tasks due today or earlier") }, ...openTodos.map((todo) => ({ type: "todo" as const, id: `todo-${todo.id}`, todo })), ...openHabits.map((habit) => ({ type: "habit" as const, id: `habit-${habit.id}`, habit }))); if (showCompleted && hiddenCompletedCount) result.push({ type: "heading", id: "today-completed", title: t("完了済み", "Completed"), detail: t("この画面だけで表示しています", "Shown only on this screen") }, ...doneTodos.map((todo) => ({ type: "todo" as const, id: `done-todo-${todo.id}`, todo })), ...doneHabits.map((habit) => ({ type: "habit" as const, id: `done-habit-${habit.id}`, habit }))); return result; }, [doneHabits, doneTodos, hiddenCompletedCount, openHabits, openTodos, showCompleted, t]);
  const openTaskForm = (defaultRequired = false) => { setNewTaskDefaultRequired(defaultRequired); setTaskFormOpen(true); };
  if (!isReady) return <ScreenContainer><LoadingScreen /></ScreenContainer>;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={listItems} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}
    ListHeaderComponent={<><View style={styles.topline}><View><Text style={[styles.date, { color: palette.primary }]}>{t("今日", "TODAY")}</Text><Text style={[styles.greeting, { color: palette.text }]}>{t("今日の予定", "Today")}</Text></View><IconButton icon="add" label={t("Todoを追加", "Add task")} onPress={() => openTaskForm()} variant="filled" /></View><TouchableOpacity onPress={() => router.push("/(tabs)/settings" as never)} activeOpacity={0.82} style={[styles.gateCard, { backgroundColor: gateLocked ? palette.elevated : palette.primarySoft, borderColor: palette.border }]}><View style={[styles.gateIcon, { backgroundColor: palette.surface }]}><MaterialIcons name={gateLocked ? "lock" : "lock-open"} size={21} color={palette.primary} /></View><View style={styles.gateCopy}><Text style={[styles.gateEyebrow, { color: palette.primary }]}>{t("アプリ制限", "APP LIMITS")}</Text><Text style={[styles.gateTitle, { color: palette.text }]}>{!gateConfig.enabled ? t("集中制限はオフです", "App limits are off") : gateLocked ? t("選択したアプリを制限中です", "Selected apps are limited") : t("今の解除条件を完了しました", "Current unlock conditions are complete")}</Text><Text style={[styles.gateDescription, { color: palette.muted }]}>{t("今日までのTodoと必須習慣が解除条件になります。", "Tasks due today or earlier and must-do habits are unlock conditions.")}</Text></View><MaterialIcons name="chevron-right" size={22} color={palette.primary} /></TouchableOpacity>{totalRequired ? <View style={[styles.progressCard, { backgroundColor: palette.primary }]}><Text style={[styles.progressLabel, { color: progressForeground }]}>{t("必須の進み具合", "MUST-DO PROGRESS")}</Text><Text style={[styles.progressTitle, { color: progressForeground }]}>{t(`残り ${pendingRequired}件`, `${pendingRequired} remaining`)}</Text><Text style={[styles.progressDetail, { color: progressForeground }]}>{t(`${doneRequired}/${totalRequired}件を完了`, `${doneRequired}/${totalRequired} complete`)}</Text></View> : null}</>}
    ListEmptyComponent={<View style={[styles.emptyPanel, { backgroundColor: palette.elevated }]}><MaterialIcons name="done-all" size={22} color={palette.primary} /><View><Text style={[styles.emptyTitle, { color: palette.text }]}>{t("今日の未完了項目はありません", "No open items for today")}</Text><Text style={[styles.emptyText, { color: palette.muted }]}>{t("新しいTodoを追加するか、明日の項目を整えましょう。", "Add a new task or plan your next action.")}</Text></View></View>}
    renderItem={({ item }) => item.type === "heading" ? <View style={[styles.sectionHeader, { backgroundColor: palette.primarySoft, borderColor: palette.border }]}><Text style={[styles.sectionTitle, { color: palette.text }]}>{item.title}</Text><Text style={[styles.sectionHint, { color: palette.muted }]}>{item.detail}</Text></View> : item.type === "todo" ? <TodoItemCard todo={item.todo} showRequired language={english ? "en" : "ja"} t={t} onToggle={() => { const result = toggleTodo(item.todo.id); safeHaptic(result.ok ? "success" : "light"); }} onOpen={() => setOpenedTodo(item.todo)} onToggleSubtask={(subtaskId) => { toggleSubtask(item.todo.id, subtaskId); }} /> : <HabitItemCard habit={item.habit} showRequired language={english ? "en" : "ja"} t={t} onToggle={(date) => { const result = toggleHabit(item.habit.id, date); safeHaptic(result.ok ? "success" : "light"); }} onStartTimer={() => { const result = startHabitTimer(item.habit.id); if (result.ok) safeHaptic("light"); }} onPauseTimer={() => { const result = pauseHabitTimer(item.habit.id); if (result.ok) safeHaptic("light"); }} onProgress={(delta) => { const result = adjustHabitProgress(item.habit.id, delta); if (result.ok && delta > 0) safeHaptic("light"); }} onOpen={() => setOpenedHabit(item.habit)} />}
    ListFooterComponent={hiddenCompletedCount ? <TouchableOpacity accessibilityRole="button" accessibilityState={{ expanded: showCompleted }} onPress={() => setShowCompleted((value) => !value)} style={[styles.revealCompleted, { backgroundColor: palette.elevated, borderColor: palette.border }]}><MaterialIcons name={showCompleted ? "visibility-off" : "visibility"} size={18} color={palette.primary} /><Text style={[styles.revealCompletedText, { color: palette.primary }]}>{showCompleted ? t("完了済みを非表示", "Hide completed") : t(`完了済みを表示（${hiddenCompletedCount}件）`, `Show completed (${hiddenCompletedCount})`)}</Text></TouchableOpacity> : null}
  /><TaskForm visible={taskFormOpen} defaultRequired={newTaskDefaultRequired} onClose={() => { setTaskFormOpen(false); setNewTaskDefaultRequired(false); }} onSave={addTodo} /><TaskForm visible={Boolean(openedTodo)} todo={openedTodo} onClose={() => setOpenedTodo(undefined)} onSave={(input) => openedTodo ? updateTodo(openedTodo.id, input) : { ok: false }} /><HabitForm visible={Boolean(openedHabit)} habit={openedHabit} onClose={() => setOpenedHabit(undefined)} onSave={(input) => openedHabit ? updateHabit(openedHabit.id, input) : { ok: false }} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 14, paddingBottom: 20, flexGrow: 1 }, topline: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 13 }, date: { fontSize: 13, fontWeight: "800", letterSpacing: 0.4 }, greeting: { fontSize: 24, lineHeight: 31, fontWeight: "800", letterSpacing: -0.4, marginTop: 2 }, gateCard: { minHeight: 86, flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 18, padding: 13, marginBottom: 10, borderWidth: 1 }, gateIcon: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" }, gateCopy: { flex: 1, minWidth: 0 }, gateEyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 0.45 }, gateTitle: { fontSize: 15, lineHeight: 20, fontWeight: "800", marginTop: 1 }, gateDescription: { fontSize: 11, lineHeight: 16, marginTop: 3 }, progressCard: { borderRadius: 18, padding: 13, marginBottom: 14 }, progressLabel: { color: "rgba(255,255,255,0.76)", fontSize: 10, fontWeight: "900", letterSpacing: 0.4 }, progressTitle: { color: COLORS.white, fontSize: 19, lineHeight: 25, fontWeight: "900", marginTop: 1 }, progressDetail: { color: "rgba(255,255,255,0.76)", fontSize: 11, lineHeight: 16, marginTop: 1 }, sectionHeader: { borderRadius: 14, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8, marginTop: 2, marginBottom: 7 }, sectionTitle: { fontSize: 16, lineHeight: 21, fontWeight: "900" }, sectionHint: { fontSize: 11, lineHeight: 15, marginTop: 1 }, emptyPanel: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 18, padding: 15, marginTop: 4 }, emptyTitle: { fontSize: 15, fontWeight: "800" }, emptyText: { fontSize: 12, lineHeight: 17, marginTop: 2 }, revealCompleted: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 14, borderWidth: 1, marginTop: 10 }, revealCompletedText: { fontSize: 13, fontWeight: "800" } });
