import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { Alert, FlatList, Modal, Platform, Pressable, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { COLORS, EmptyState, IconButton, LoadingScreen, safeHaptic, ScreenHeading } from "@/components/focus-flow/ui";
import { ScreenContainer } from "@/components/screen-container";
import { useFocusFlow } from "@/lib/focus-flow/provider";
import type { Memo } from "@/lib/focus-flow/types";

export default function NotesScreen() {
  const { memos, isReady, addMemo, updateMemo, deleteMemo, addTodo } = useFocusFlow();
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<Memo | undefined>();
  const openForm = (memo?: Memo) => { setEditing(memo); setFormOpen(true); };
  const remove = (memo: Memo) => {
    const confirm = () => deleteMemo(memo.id);
    if (Platform.OS === "web") confirm();
    else Alert.alert("メモを削除しますか？", "削除したメモは復元できません。", [{ text: "キャンセル", style: "cancel" }, { text: "削除", style: "destructive", onPress: confirm }]);
  };
  const convert = (memo: Memo) => {
    const confirm = () => { addTodo({ title: memo.title, priority: "medium", isRequired: false }); safeHaptic("success"); };
    if (Platform.OS === "web") confirm();
    else Alert.alert("Todoに追加", `「${memo.title}」を通常のTodoとして追加します。`, [{ text: "キャンセル", style: "cancel" }, { text: "追加", onPress: confirm }]);
  };
  if (!isReady) return <ScreenContainer><LoadingScreen /></ScreenContainer>;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={memos} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<ScreenHeading eyebrow="あとで整理する" title="メモ" action={<IconButton icon="add" label="メモを追加" onPress={() => openForm()} variant="filled" />} />} ListEmptyComponent={<EmptyState icon="sticky-note-2" title="気になったことをすぐ残す" description="まだTodoにしない情報、考え、調べたいことを自由にメモできます。" actionLabel="メモを追加" onAction={() => openForm()} />} renderItem={({ item }) => <View style={styles.memoCard}><TouchableOpacity onPress={() => openForm(item)} activeOpacity={0.76} style={styles.memoCopy}><Text style={styles.memoTitle} numberOfLines={1}>{item.title}</Text>{item.body ? <Text style={styles.memoBody} numberOfLines={3}>{item.body}</Text> : null}<Text style={styles.memoDate}>{new Date(item.updatedAt).toLocaleDateString("ja-JP", { month: "numeric", day: "numeric" })} 更新</Text></TouchableOpacity><View style={styles.actions}><TouchableOpacity accessibilityLabel="Todoとして追加" onPress={() => convert(item)} style={styles.action}><MaterialIcons name="playlist-add" size={20} color={COLORS.blue} /></TouchableOpacity><TouchableOpacity accessibilityLabel="メモを削除" onPress={() => remove(item)} style={styles.action}><MaterialIcons name="more-horiz" size={21} color={COLORS.muted} /></TouchableOpacity></View></View>} /><MemoForm visible={formOpen} memo={editing} onClose={() => { setFormOpen(false); setEditing(undefined); }} onSave={(input) => editing ? updateMemo(editing.id, input) : addMemo(input)} /></ScreenContainer>;
}

function MemoForm({ visible, memo, onClose, onSave }: { visible: boolean; memo?: Memo; onClose: () => void; onSave: (input: { title?: string; body: string }) => void }) { const [title, setTitle] = useState(""); const [body, setBody] = useState(""); useEffect(() => { if (visible) { setTitle(memo?.title ?? ""); setBody(memo?.body ?? ""); } }, [visible, memo]); const save = () => { if (!title.trim() && !body.trim()) return; onSave({ title, body }); onClose(); }; return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose}><Pressable style={styles.sheet} onPress={() => undefined}><View style={styles.handle} /><View style={styles.formHeader}><Text style={styles.formTitle}>{memo ? "メモを編集" : "メモを追加"}</Text><TouchableOpacity onPress={onClose} style={styles.close}><MaterialIcons name="close" size={20} color={COLORS.muted} /></TouchableOpacity></View><TextInput value={title} onChangeText={setTitle} placeholder="タイトル（任意）" placeholderTextColor="#91A0B7" style={styles.titleInput} autoFocus={!memo} /><TextInput value={body} onChangeText={setBody} placeholder="思いつき、調べたいこと、あとで決めること…" placeholderTextColor="#91A0B7" style={styles.bodyInput} multiline textAlignVertical="top" /><TouchableOpacity onPress={save} disabled={!title.trim() && !body.trim()} style={[styles.save, !title.trim() && !body.trim() && styles.saveDisabled]}><Text style={styles.saveText}>{memo ? "変更を保存" : "メモを保存"}</Text></TouchableOpacity></Pressable></Pressable></Modal>; }

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 28, flexGrow: 1 }, memoCard: { flexDirection: "row", backgroundColor: "rgba(255,255,255,0.78)", borderColor: "#D7E1F0", borderWidth: 1, borderRadius: 18, padding: 14, marginBottom: 9 }, memoCopy: { flex: 1, minWidth: 0 }, memoTitle: { color: COLORS.text, fontSize: 16, lineHeight: 21, fontWeight: "800" }, memoBody: { color: COLORS.muted, fontSize: 13, lineHeight: 19, marginTop: 5 }, memoDate: { color: "#7B8AA3", fontSize: 11, fontWeight: "700", marginTop: 9 }, actions: { width: 37, alignItems: "center", gap: 4 }, action: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#EDF3FB" }, backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(22,35,59,0.34)" }, sheet: { backgroundColor: "#F4F8FE", borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 20, paddingBottom: 34 }, handle: { alignSelf: "center", width: 42, height: 5, borderRadius: 3, backgroundColor: "#C8D5E8", marginTop: 10, marginBottom: 16 }, formHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }, formTitle: { color: COLORS.text, fontSize: 20, fontWeight: "800" }, close: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#E9F0FA" }, titleInput: { minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: "#D7E1F0", backgroundColor: "rgba(255,255,255,0.82)", color: COLORS.text, fontSize: 16, paddingHorizontal: 13, marginBottom: 10 }, bodyInput: { minHeight: 136, borderRadius: 13, borderWidth: 1, borderColor: "#D7E1F0", backgroundColor: "rgba(255,255,255,0.82)", color: COLORS.text, fontSize: 15, lineHeight: 22, padding: 13 }, save: { minHeight: 51, alignItems: "center", justifyContent: "center", borderRadius: 16, backgroundColor: COLORS.forest, marginTop: 16 }, saveDisabled: { backgroundColor: "#AAB8C9" }, saveText: { color: COLORS.white, fontSize: 16, fontWeight: "800" } });
